# Generated by Django 2.1.4 on 2018-12-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='value',
            field=models.ImageField(upload_to='images/media/images/'),
        ),
    ]
