# Generated by Django 2.1.4 on 2018-12-24 11:31

from django.db import migrations, models
import django.db.models.deletion
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181224_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=products.utils.get_default_category,
                                    on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
