# Generated by Django 2.1.4 on 2018-12-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='D:\\Учеба\\python_django\\hw3\\server\\main\\static\\media\\main'),
        ),
    ]
