# Generated by Django 2.1.4 on 2018-12-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181223_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
