# Generated by Django 2.1.4 on 2018-12-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
